# Generated by Django 2.2.6 on 2019-11-06 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0003_redaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='redact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='p_library.Redaction'),
            preserve_default=False,
        ),
    ]
