# Generated by Django 2.2.6 on 2019-11-18 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_auto_20191113_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='friendbook',
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.SmallIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_library.Book')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_library.Friend')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend', through='p_library.Rent', to='p_library.Friend'),
        ),
    ]
