# Generated by Django 2.2.6 on 2019-11-21 09:36

from django.db import migrations, models
import p_library.models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0006_auto_20191118_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copy_count',
            field=models.SmallIntegerField(default=2, validators=[p_library.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='book',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friendrent', through='p_library.Rent', to='p_library.Friend'),
        ),
    ]
