# Generated by Django 2.2.6 on 2019-11-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0010_auto_20191121_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='redaction',
            name='city',
            field=models.CharField(default='Moscow', max_length=60),
            preserve_default=False,
        ),
    ]
